// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.

export type ImageVariant = { src: number; w: number };
export type ImageVariantEntry = {
  w: number;
  h: number;
  webp: ImageVariant[];
};

export const imageVariants: Record<string, ImageVariantEntry> = {
  "involvement/girlup.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/involvement/girlup.w480.webp'), w: 480 },
      { src: require('../../../assets/images/involvement/girlup.w960.webp'), w: 960 },
    ],
  },
  "involvement/leo-club.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/involvement/leo-club.w480.webp'), w: 480 },
      { src: require('../../../assets/images/involvement/leo-club.w960.webp'), w: 960 },
    ],
  },
  "involvement/xcc.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/involvement/xcc.w480.webp'), w: 480 },
      { src: require('../../../assets/images/involvement/xcc.w960.webp'), w: 960 },
    ],
  },
  "logos/envision-x.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/logos/envision-x.w480.webp'), w: 480 },
      { src: require('../../../assets/images/logos/envision-x.w960.webp'), w: 960 },
    ],
  },
  "logos/hobiz.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/logos/hobiz.w480.webp'), w: 480 },
      { src: require('../../../assets/images/logos/hobiz.w960.webp'), w: 960 },
    ],
  },
  "logos/story-of-strings.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/logos/story-of-strings.w480.webp'), w: 480 },
      { src: require('../../../assets/images/logos/story-of-strings.w960.webp'), w: 960 },
    ],
  },
  "logos/xpert.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/logos/xpert.w480.webp'), w: 480 },
      { src: require('../../../assets/images/logos/xpert.w960.webp'), w: 960 },
    ],
  },
  "personal.png": {
    w: 1080, h: 1350,
    webp: [
      { src: require('../../../assets/images/personal.w480.webp'), w: 480 },
      { src: require('../../../assets/images/personal.w960.webp'), w: 960 },
    ],
  },
  "riwayat/1.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/riwayat/1.w480.webp'), w: 480 },
      { src: require('../../../assets/images/riwayat/1.w960.webp'), w: 960 },
    ],
  },
  "riwayat/2.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/riwayat/2.w480.webp'), w: 480 },
      { src: require('../../../assets/images/riwayat/2.w960.webp'), w: 960 },
    ],
  },
  "riwayat/3.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/riwayat/3.w480.webp'), w: 480 },
      { src: require('../../../assets/images/riwayat/3.w960.webp'), w: 960 },
    ],
  },
  "riwayat/4.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/riwayat/4.w480.webp'), w: 480 },
      { src: require('../../../assets/images/riwayat/4.w960.webp'), w: 960 },
    ],
  },
  "sos/coming-soon.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/coming-soon.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/coming-soon.w960.webp'), w: 960 },
    ],
  },
  "sos/desk-to-dinner.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/desk-to-dinner.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/desk-to-dinner.w960.webp'), w: 960 },
    ],
  },
  "sos/embroidered-panel.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/embroidered-panel.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/embroidered-panel.w960.webp'), w: 960 },
    ],
  },
  "sos/fruits-embroidery/1.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/fruits-embroidery/1.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/fruits-embroidery/1.w960.webp'), w: 960 },
    ],
  },
  "sos/fruits-embroidery/2.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/fruits-embroidery/2.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/fruits-embroidery/2.w960.webp'), w: 960 },
    ],
  },
  "sos/fruits-embroidery/3.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/fruits-embroidery/3.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/fruits-embroidery/3.w960.webp'), w: 960 },
    ],
  },
  "sos/fruits-embroidery/4.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/fruits-embroidery/4.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/fruits-embroidery/4.w960.webp'), w: 960 },
    ],
  },
  "sos/fruits-embroidery/5.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/fruits-embroidery/5.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/fruits-embroidery/5.w960.webp'), w: 960 },
    ],
  },
  "sos/khaka-designs/1.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/khaka-designs/1.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/khaka-designs/1.w960.webp'), w: 960 },
    ],
  },
  "sos/khaka-designs/2.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/khaka-designs/2.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/khaka-designs/2.w960.webp'), w: 960 },
    ],
  },
  "sos/khaka-designs/3.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/khaka-designs/3.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/khaka-designs/3.w960.webp'), w: 960 },
    ],
  },
  "sos/khaka-designs/4.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/khaka-designs/4.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/khaka-designs/4.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/1.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/1.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/1.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/2.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/2.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/2.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/3.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/3.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/3.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/4.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/4.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/4.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/5.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/5.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/5.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/6.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/6.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/6.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/7.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/7.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/7.w960.webp'), w: 960 },
    ],
  },
  "sos/shapes-embroidery/8.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/shapes-embroidery/8.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/shapes-embroidery/8.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/1.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/1.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/1.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/2.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/2.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/2.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/3.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/3.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/3.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/4.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/4.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/4.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/5.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/5.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/5.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/6.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/6.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/6.w960.webp'), w: 960 },
    ],
  },
  "sos/types-of-personality/7.png": {
    w: 1080, h: 1080,
    webp: [
      { src: require('../../../assets/images/sos/types-of-personality/7.w480.webp'), w: 480 },
      { src: require('../../../assets/images/sos/types-of-personality/7.w960.webp'), w: 960 },
    ],
  },
  "xpert-linkedin/1.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/xpert-linkedin/1.w480.webp'), w: 480 },
      { src: require('../../../assets/images/xpert-linkedin/1.w960.webp'), w: 960 },
    ],
  },
  "xpert-linkedin/2.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/xpert-linkedin/2.w480.webp'), w: 480 },
      { src: require('../../../assets/images/xpert-linkedin/2.w960.webp'), w: 960 },
    ],
  },
  "xpert-linkedin/3.png": {
    w: 1080, h: 810,
    webp: [
      { src: require('../../../assets/images/xpert-linkedin/3.w480.webp'), w: 480 },
      { src: require('../../../assets/images/xpert-linkedin/3.w960.webp'), w: 960 },
    ],
  },
};
